using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Archive.Import.Synthetic;

/// <summary>Shape of a generated archive.</summary>
/// <param name="Messages">Roughly how many messages to produce.</param>
/// <param name="Chats">How many conversations to spread them across.</param>
/// <param name="Seed">Fixed so a given size always produces the identical export.</param>
/// <param name="StartUtc">When the archive begins.</param>
/// <param name="EndUtc">When it ends.</param>
public sealed record SyntheticOptions(
    int Messages = 10_000,
    int Chats = 20,
    int Seed = 20260909,
    DateTimeOffset? StartUtc = null,
    DateTimeOffset? EndUtc = null);

/// <summary>
/// Writes a Telegram-shaped export with no real data in it.
/// </summary>
/// <remarks>
/// <para>
/// A development aid, for two things a small fixture cannot do: giving someone a populated
/// archive to look at before they have exported their own, and measuring the app at a size where
/// the query plans actually matter. It ships in the library rather than in a test project so the
/// CLI and the performance tests use one implementation.
/// </para>
/// <para>
/// It deliberately reproduces the properties that make real archives awkward — bursts separated
/// by months of silence, a long tail of two-word messages, Cyrillic alongside Latin, timestamps
/// colliding within a second, the same sticker repeated everywhere, replies, edits and reactions.
/// Volume alone would measure the wrong thing.
/// </para>
/// <para>
/// It cannot substitute for a real export when it comes to <em>parsing</em>: it only produces
/// shapes the importer already knows about, so it can never surface a trap nobody has thought of.
/// That is what a real export is for.
/// </para>
/// </remarks>
public static class SyntheticExport
{
    private const long OwnerId = 777001;

    private static readonly string[] English =
    [
        "ok", "yeah", "sure", "on my way", "sorry, missed this", "let me check",
        "the harbour was freezing", "we should go back", "booked the tickets",
        "shall we take the early train", "that place near the station", "next week works",
        "call you tonight", "no worries", "same here", "sounds good", "just landed",
        "running about ten minutes late", "did you see the photos", "thanks for sorting that",
    ];

    private static readonly string[] Cyrillic =
    [
        "привет", "как дела", "давай", "хорошо", "не могу сегодня", "перезвоню",
        "Прага была холодной", "мы были в Праге весной", "поезд в 07:40",
        "встретимся у вокзала", "спасибо большое", "до завтра", "уже еду",
        "буду через двадцать минут", "нашёл билеты", "всё в порядке", "договорились",
    ];

    private static readonly string[] FirstNames =
    [
        "Sam", "Alex", "Kim", "Robin", "Марина", "Дмитрий", "Олена", "Jo", "Chris", "Ана",
    ];

    private static readonly string[] LastNames =
    [
        "Ruiz", "Novak", "Fisher", "Weber", "Коваль", "Петров", "Шевченко", "Lang", "Bauer", "Дуб",
    ];

    /// <summary>
    /// Writes <c>result.json</c> and a small media folder into <paramref name="folder"/>.
    /// </summary>
    /// <remarks>
    /// Streamed with <see cref="Utf8JsonWriter"/> rather than built in memory: a million-message
    /// export is hundreds of megabytes, and a generator that cannot produce one without exhausting
    /// memory is not much use for measuring one.
    /// </remarks>
    public static SyntheticSummary Write(string folder, SyntheticOptions? options = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(folder);

        options ??= new SyntheticOptions();

        Directory.CreateDirectory(folder);

        var random = new Random(options.Seed);
        var start = options.StartUtc ?? new DateTimeOffset(2016, 1, 1, 0, 0, 0, TimeSpan.Zero);
        var end = options.EndUtc ?? new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);

        var contacts = BuildContacts(random, options.Chats);
        var stickerPath = WriteMedia(folder, random);

        var perChat = Math.Max(1, options.Messages / Math.Max(1, options.Chats));
        var written = 0;

        using var stream = File.Create(Path.Combine(folder, "result.json"));
        using var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = false });

        writer.WriteStartObject();
        writer.WriteString("about", "Synthetic export generated by ahistory. Contains no real data.");

        writer.WriteStartObject("personal_information");
        writer.WriteNumber("user_id", OwnerId);
        writer.WriteString("first_name", "Owner");
        writer.WriteString("last_name", "Synthetic");
        writer.WriteString("username", "owner");
        writer.WriteEndObject();

        writer.WriteStartObject("chats");
        writer.WriteString("about", "Chats.");
        writer.WriteStartArray("list");

        for (var c = 0; c < options.Chats; c++)
        {
            written += WriteChat(writer, random, contacts, c, perChat, start, end, stickerPath);
        }

        writer.WriteEndArray();
        writer.WriteEndObject();
        writer.WriteEndObject();
        writer.Flush();

        return new SyntheticSummary(
            folder, written, options.Chats, contacts.Count, new FileInfo(Path.Combine(folder, "result.json")).Length);
    }

    private static List<Contact> BuildContacts(Random random, int count)
    {
        var contacts = new List<Contact>(count);

        for (var i = 0; i < Math.Max(2, count); i++)
        {
            var name = $"{FirstNames[random.Next(FirstNames.Length)]} {LastNames[random.Next(LastNames.Length)]}";
            contacts.Add(new Contact(5000 + i, name));
        }

        return contacts;
    }

    /// <summary>
    /// One small file, referenced from many messages.
    /// </summary>
    /// <remarks>
    /// §1: exports repeat the same sticker hundreds of times, and the media store's whole job is
    /// to notice. A generator that gave every message a unique file would measure the opposite.
    /// </remarks>
    private static string WriteMedia(string folder, Random random)
    {
        var stickers = Path.Combine(folder, "stickers");
        Directory.CreateDirectory(stickers);

        var bytes = new byte[2048];
        random.NextBytes(bytes);
        File.WriteAllBytes(Path.Combine(stickers, "sticker.webp"), bytes);

        return "stickers/sticker.webp";
    }

    private static int WriteChat(
        Utf8JsonWriter writer,
        Random random,
        List<Contact> contacts,
        int index,
        int messageCount,
        DateTimeOffset start,
        DateTimeOffset end,
        string stickerPath)
    {
        var isGroup = index % 4 == 3;
        var contact = contacts[index % contacts.Count];

        writer.WriteStartObject();
        writer.WriteString("name", isGroup ? $"Group {index}" : contact.Name);
        writer.WriteString("type", isGroup ? "private_group" : "personal_chat");
        writer.WriteNumber("id", 100 + index);
        writer.WriteStartArray("messages");

        // Conversations happen in bursts with long gaps between them, which is what makes silence
        // dividers and session segmentation meaningful.
        var cursor = start.AddSeconds(random.NextDouble() * (end - start).TotalSeconds * 0.1);
        var written = 0;
        var id = 1;

        const int AverageBurst = 30;

        // The gap between bursts is derived from how many are left and how much time remains,
        // rather than picked from a fixed range. A fixed range exhausts a ten-year window long
        // before a large message count is reached, and quietly produces a quarter of what was
        // asked for.
        var burstsRemaining = Math.Max(1, messageCount / AverageBurst);

        while (written < messageCount && cursor < end)
        {
            var burst = Math.Min(messageCount - written, random.Next(3, AverageBurst * 2));

            for (var b = 0; b < burst; b++)
            {
                // Same-second collisions are constant in real exports, and they are exactly what
                // breaks paging that has no tie-break.
                cursor = cursor.AddSeconds(random.Next(0, 2) == 0 ? 0 : random.Next(5, 400));

                var fromOwner = random.Next(2) == 0;
                var speaker = fromOwner ? null : PickSender(random, contacts, contact, isGroup);

                WriteMessage(
                    writer, random, id++, cursor,
                    speaker?.Id ?? OwnerId,
                    speaker?.Name ?? "Owner Synthetic",
                    isGroup, stickerPath);
                written++;
            }

            burstsRemaining = Math.Max(1, burstsRemaining - 1);

            var averageGap = Math.Max(60, (end - cursor).TotalSeconds / burstsRemaining);

            // Randomized around that average, so silences vary from short to very long.
            cursor = cursor.AddSeconds(averageGap * (0.15 + (random.NextDouble() * 1.7)));
        }

        writer.WriteEndArray();
        writer.WriteEndObject();

        return written;
    }

    /// <summary>In a group anyone might speak; in a direct chat it is always the same person.</summary>
    private static Contact PickSender(Random random, List<Contact> contacts, Contact primary, bool isGroup) =>
        isGroup ? contacts[random.Next(contacts.Count)] : primary;

    private static void WriteMessage(
        Utf8JsonWriter writer,
        Random random,
        int id,
        DateTimeOffset at,
        long senderId,
        string senderName,
        bool isGroup,
        string stickerPath)
    {
        writer.WriteStartObject();
        writer.WriteNumber("id", id);

        // A small share of service messages, because routing those through the normal sender path
        // is §2's phantom-people trap.
        if (random.Next(100) < 2)
        {
            writer.WriteString("type", "service");
            writer.WriteString("date", at.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture));
            writer.WriteString("date_unixtime", at.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture));
            writer.WriteString("actor", senderName);
            writer.WriteString("actor_id", "user" + senderId.ToString(CultureInfo.InvariantCulture));
            writer.WriteString("action", isGroup ? "invite_members" : "phone_call");
            writer.WriteString("text", string.Empty);
            writer.WriteStartArray("text_entities");
            writer.WriteEndArray();
            writer.WriteEndObject();
            return;
        }

        writer.WriteString("type", "message");
        writer.WriteString("date", at.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture));
        writer.WriteString("date_unixtime", at.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture));
        writer.WriteString("from", senderName);
        writer.WriteString("from_id", "user" + senderId.ToString(CultureInfo.InvariantCulture));

        if (id > 1 && random.Next(100) < 20)
        {
            writer.WriteNumber("reply_to_message_id", random.Next(1, id));
        }

        if (random.Next(100) < 5)
        {
            writer.WriteString("edited_unixtime", at.AddMinutes(2).ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture));
        }

        // The same sticker everywhere, so the media store has something to deduplicate.
        if (random.Next(100) < 6)
        {
            writer.WriteString("file", stickerPath);
            writer.WriteString("media_type", "sticker");
            writer.WriteString("sticker_emoji", "🐢");
            writer.WriteString("mime_type", "image/webp");
        }

        var text = BuildText(random);

        writer.WriteString("text", text);
        writer.WriteStartArray("text_entities");
        writer.WriteStartObject();
        writer.WriteString("type", "plain");
        writer.WriteString("text", text);
        writer.WriteEndObject();
        writer.WriteEndArray();

        if (random.Next(100) < 8)
        {
            writer.WriteStartArray("reactions");
            writer.WriteStartObject();
            writer.WriteString("type", "emoji");
            writer.WriteNumber("count", random.Next(1, 6));
            writer.WriteString("emoji", "👍");
            writer.WriteEndObject();
            writer.WriteEndArray();
        }

        writer.WriteEndObject();
    }

    /// <summary>
    /// Message text with a realistic length distribution.
    /// </summary>
    /// <remarks>
    /// §6.2: a large fraction of real messages are two words of logistics. Generating uniformly
    /// long text would make search, indexing and future extraction all look easier than they are.
    /// </remarks>
    private static string BuildText(Random random)
    {
        var cyrillic = random.Next(100) < 35;
        var pool = cyrillic ? Cyrillic : English;

        var parts = random.Next(100) switch
        {
            < 55 => 1,
            < 85 => 2,
            < 97 => 4,
            _ => 12,
        };

        var builder = new StringBuilder();

        for (var i = 0; i < parts; i++)
        {
            if (i > 0)
            {
                builder.Append(' ');
            }

            builder.Append(pool[random.Next(pool.Length)]);
        }

        return builder.ToString();
    }

    private sealed record Contact(long Id, string Name);
}

/// <summary>What a generated export contains.</summary>
public sealed record SyntheticSummary(
    string Folder, int Messages, int Chats, int Contacts, long JsonBytes);
