namespace Archive.Data;

/// <summary>Two accounts that might belong to the same human.</summary>
/// <param name="Reason">Why they were paired, in words the UI can show.</param>
/// <param name="Strength">
/// How much the evidence is worth, higher first. Not a probability: an ordering, so the pairs
/// worth looking at come before the ones worth ignoring.
/// </param>
public sealed record MergeSuggestion(
    string LeftIdentityId,
    string LeftDisplayName,
    string LeftPlatform,
    string LeftPersonId,
    string LeftPersonName,
    string RightIdentityId,
    string RightDisplayName,
    string RightPlatform,
    string RightPersonId,
    string RightPersonName,
    bool TouchesOwner,
    string Reason,
    int Strength);

/// <summary>
/// Accounts that look like the same person, offered rather than applied.
/// </summary>
/// <remarks>
/// <para>
/// §1 is explicit that auto-matching on names and phone numbers produces wrong merges, and the
/// plan declined to do it for a reason worth repeating: an under-merge is untidy and reversible in
/// one click, while an over-merge is a confident lie — every fact one person stated becomes a fact
/// about another, and §7's knowledge base has no way to tell.
/// </para>
/// <para>
/// So nothing here writes anything. It produces a list; the user says yes to a row, and
/// <see cref="IdentityMerger"/> does the merge with the same owner confirmation as any other. What
/// this changes is that finding the pairs is no longer the user's job — scanning a thousand
/// accounts by eye is how a merge feature goes unused.
/// </para>
/// </remarks>
public sealed class MergeSuggestions(Database database)
{
    private readonly Database _database = database ?? throw new ArgumentNullException(nameof(database));

    /// <summary>
    /// Pairs worth offering, best first.
    /// </summary>
    /// <param name="limit">
    /// How many to return. A cap rather than a page: this is a list to work through, and an
    /// archive with four hundred plausible pairs in it needs the best twenty, not all of them.
    /// </param>
    public IReadOnlyList<MergeSuggestion> Candidates(int limit = 50)
    {
        using var connection = _database.Open();
        using var command = connection.CreateCommand();

        // Pairs are generated by joining identity to itself on a normalized name or on a handle,
        // with a < b so each pair appears once. Excluded: identities already on one person
        // (nothing to merge), and pairs the user has already turned down.
        //
        // Normalizing with lower() rather than a collation: the tables are STRICT and BINARY, and
        // adding NOCASE here would change what the unique indexes mean.
        command.CommandText = """
            SELECT a.id, a.display_name, a.platform, pa.id, pa.display_name,
                   b.id, b.display_name, b.platform, pb.id, pb.display_name,
                   max(ifnull(pa.is_owner, 0), ifnull(pb.is_owner, 0)),
                   CASE
                       WHEN a.handle IS NOT NULL AND a.handle = b.handle THEN 'handle'
                       WHEN a.platform <> b.platform THEN 'cross'
                       ELSE 'synthetic'
                   END,
                   (SELECT count(*) FROM message m WHERE m.sender_identity_id = a.id)
                     + (SELECT count(*) FROM message m WHERE m.sender_identity_id = b.id),
                   -- How much the evidence is worth. An ordering, not a probability: 30 is a
                   -- shared handle, 20 the same name on two platforms, 10 the same name where one
                   -- side is a name with no account behind it. Kept here rather than in C# so the
                   -- ranking and the LIMIT that truncates it cannot disagree.
                   CASE
                       WHEN a.handle IS NOT NULL AND a.handle = b.handle THEN 30
                       WHEN a.platform <> b.platform THEN 20
                       ELSE 10
                   END
            FROM identity a
            JOIN identity b
              ON b.id > a.id
             AND (
                   (a.handle IS NOT NULL AND a.handle <> '' AND a.handle = b.handle)
                   OR lower(a.display_name) = lower(b.display_name)
                 )
            JOIN identity_person ipa ON ipa.identity_id = a.id
            JOIN identity_person ipb ON ipb.identity_id = b.id
            JOIN person pa ON pa.id = ipa.person_id
            JOIN person pb ON pb.id = ipb.person_id
            WHERE ipa.person_id <> ipb.person_id
              AND NOT EXISTS (
                    SELECT 1 FROM merge_dismissal d
                    WHERE d.left_identity_id = a.id AND d.right_identity_id = b.id)
              -- Two accounts on one platform with the same name are two different people unless
              -- one of them is a name with no id behind it (§2). Telegram will not let two
              -- accounts share a username, and a name collision there is a coincidence.
              AND (a.platform <> b.platform
                   OR a.is_synthetic = 1
                   OR b.is_synthetic = 1
                   OR (a.handle IS NOT NULL AND a.handle = b.handle))
            -- Strength first, then how much was said. The limit is a cap on a ranked list, so it
            -- has to be applied to the ranking the user will see: ordering by volume and
            -- re-sorting afterwards would cut a strong pair with few messages before it was ever
            -- ranked, which is the one kind of suggestion worth surfacing most.
            ORDER BY 14 DESC, 13 DESC, a.display_name
            LIMIT $limit;
            """;
        command.Parameters.AddWithValue("$limit", limit);

        var suggestions = new List<MergeSuggestion>();
        using var reader = command.ExecuteReader();

        while (reader.Read())
        {
            var reason = reader.GetString(11) switch
            {
                "handle" => "Both accounts use the same handle.",
                "cross" => $"The same name on {Platform(reader.GetString(2))} and {Platform(reader.GetString(7))}.",
                _ => "The same name, and one of them is a name with no account behind it.",
            };

            suggestions.Add(new MergeSuggestion(
                reader.GetString(0), reader.GetString(1), reader.GetString(2),
                reader.GetString(3), reader.GetString(4),
                reader.GetString(5), reader.GetString(6), reader.GetString(7),
                reader.GetString(8), reader.GetString(9),
                reader.GetInt64(10) == 1,
                reason,
                (int)reader.GetInt64(13)));
        }

        return suggestions;
    }

    /// <summary>
    /// Records that these two are not the same person, so the pair stops being offered.
    /// </summary>
    /// <remarks>
    /// A list that re-offers what it has already been told is wrong is one people stop reading,
    /// and the pairs it is most confidently wrong about are the ones it will keep suggesting.
    /// </remarks>
    public void Dismiss(string identityId, string otherIdentityId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identityId);
        ArgumentException.ThrowIfNullOrWhiteSpace(otherIdentityId);

        var (left, right) = Order(identityId, otherIdentityId);

        using var connection = _database.Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO merge_dismissal (left_identity_id, right_identity_id, dismissed_utc)
            VALUES ($left, $right, $now)
            ON CONFLICT (left_identity_id, right_identity_id) DO NOTHING;
            """;
        command.Parameters.AddWithValue("$left", left);
        command.Parameters.AddWithValue("$right", right);
        command.Parameters.AddWithValue("$now", DateTimeOffset.UtcNow.ToString("O"));
        command.ExecuteNonQuery();
    }

    /// <summary>Takes back a dismissal, for a user who changed their mind.</summary>
    public void Restore(string identityId, string otherIdentityId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identityId);
        ArgumentException.ThrowIfNullOrWhiteSpace(otherIdentityId);

        var (left, right) = Order(identityId, otherIdentityId);

        using var connection = _database.Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
            DELETE FROM merge_dismissal
            WHERE left_identity_id = $left AND right_identity_id = $right;
            """;
        command.Parameters.AddWithValue("$left", left);
        command.Parameters.AddWithValue("$right", right);
        command.ExecuteNonQuery();
    }

    /// <summary>The pair in the fixed order the table's CHECK constraint requires.</summary>
    private static (string Left, string Right) Order(string first, string second) =>
        string.CompareOrdinal(first, second) < 0 ? (first, second) : (second, first);

    /// <summary>A platform id as a person would say it.</summary>
    private static string Platform(string id) => id switch
    {
        "telegram" => "Telegram",
        "hangouts" => "Google Hangouts",
        "googlechat" => "Google Chat",
        "messenger" => "Facebook Messenger",
        "instagram" => "Instagram",
        "sms" => "SMS",
        "whatsapp" => "WhatsApp",
        "skype" => "Skype",
        "vk" => "VKontakte",
        "qip" => "QIP",
        var other => other,
    };
}
